// prettier-ignore
const translation = {
  Global: {
    EnterPin: 'Enter PIN',
    EnterNewPin: 'Enter New PIN',
    SixDigitPin: '6 Digit PIN',
    Submit: 'Submit',
    Cancel: 'Cancel',
    Confirm: 'Confirm',
    Accept: 'Accept',
    Reject: 'Reject',
    Share: 'Share',
    Decline: 'Decline',
    Back: 'Back',
    Next: 'Next',
    Continue: 'Continue',
    Info: 'Information',
    Failure: 'Failure',
    Success: 'Success',
    SomethingWentWrong: 'Something went wrong',
    Done: 'Done',
    Skip: 'Skip',
    Previous: 'Prev',
    View: 'View',
    Home: 'Home',
    ErrorCode: 'Error Code',
    Okay: 'Okay',
    Verify: 'Verify',
    ChangePin: 'Change PIN',
    OldPin: 'Enter Old PIN',
    Copy: 'Copy',
    from: 'from',
    Yes: 'Yes',
    No: 'No',
    ThisDecisionCannotBeChanged: 'This decision cannot be changed.',
    ZeroRecords: 'No records available',
    ImportWallet: 'Import Wallet',
    UserInactivity: 'Logging out due to inactivity',
  },
  Language: {
    English: 'English',
    French: 'French',
    German: 'German',
  },
  Registration:{
    RegisterAgain: 'Please register again',
    MnemonicMsg: 'This phrase is the only way to export and import wallet, save it somewhere safe and secret. The phrase can be later found under the settings tab.',
    Passphrase: 'Passphrase',
    Mnemonic: 'Mnemonic',
    SecondCounter: 'Seconds Left',
    WalletInitialized:'Wallet initialized successfully.',
  },
  Terms: {
    AcceptTerms: 'This software is licensed as open source software under the <apachelink>Apache License Version 2.0</apachelink> and is governed by a firm commitment to your privacy and personal data, as explained in detail in our <privacylink>Privacy Policy</privacylink>.',
    AcceptTermsContinue: 'Please only continue, in case you have noted and accepted the indicated documents.',
  },
  PinCreate: {
    UserAuthenticationPin: 'User authentication pin',
    PinMustBe6DigitsInLength: 'PIN must be 6 digits in length',
    ReEnterPinMustBe6DigitsInLength: 'Insufficient PIN length',
    PinsEnteredDoNotMatch: 'PIN entered does not match',
    PinsSuccess: 'PIN created successfully',
    PinChange: 'PIN changed successfully',
    NewPinMatchWithOld: 'New PIN is same as the Old PIN',
    SixDigitPin: '6 Digit PIN',
    ReenterPin: 'Re-Enter PIN',
    ReenterNewPin: 'Re-Enter the New PIN',
    Create: 'Create',
    ValidOldPin: 'Please enter valid Old PIN',
    WalletCreated: 'The wallet is created successfully.',
    OR: 'OR',
    PinInfo: 'This pin is used for login',
    ChangePin: 'Change PIN',
  },
  Biometric: {
    Biometric: 'Biometric',
    BiometricConfirm: 'Confirm fingerprint',
    BiometricSuccess: 'Fingerprint configured successfully',
    BiometricFailed: 'Biometrics failed',
    BiometricCancel: 'User cancelled the biometric prompt',
    BiometricNotSupport: 'Biometrics not supported',
    RegisterPinandBiometric: 'Register PIN and Biometric',
    BiometricInfo: 'Register Biometric use for login',
  },
  Initialization:{
    CompleteInitialization:'Complete the initialization',
    InitializationInfo:'Initialize new wallet or import old wallet',
    ImportWalletBtn: 'Import Wallet',
    InitializationBtn: 'Initialization',
  },
  Mnemonic:{
    MnemonicTitle:'Below is the mnemonic for future references',
  },
  Home: {
    Welcome: 'Welcome',
    Notifications: 'Notifications',
    NoNewUpdates: 'There is no new notification.',
    NoCredentials: 'There are no credentials in the wallet.',
    SeeAll: 'See all',
    YouHave: 'You have',
    Credential: 'credential',
    Credentials: 'credentials',
    InYourWallet: 'in your wallet',
    CredentialCountUndefinedError:'Credential count cannot be undefined',
  },
  PinEnter: {
    IncorrectPin: 'Incorrect PIN',
  },
  Settings: {
    ChangePin: 'Change PIN',
    Version: 'Version',
    AppPreferences: 'App Preferences',
    AboutApp: 'About App',
    Language: 'Language',
    Logout: 'Logout',
    LogoutMsg: 'Please confirm to logout',
    MnemonicMsg: 'Mnemonic can not be blank',
    EnterMnemonic: 'Enter Mnemonic',
    ValidMnemonic: 'Valid Mnemonic',
    InvalidMnemonic: 'Invalid Mnemonic',
    LegalAndPrivacy: 'Legal & Privacy',
    ExportWallet: 'Export Wallet',
    ViewMnemonic: 'View Mnemonic',
    RemoveDataTitle: 'Delete account',
    RemoveDataButton: 'Remove All Data',
    RemoveDataMsg: 'You are going to remove the wallet from your phone. The added connections and credentials will be removed from the app. Are you sure to continue?',
  },
  ExportWallet:{
    WalletExportedPath: 'Wallet Exported to the path:',
  },
  ImportWallet:{
    SelectWalletFile: 'Select Wallet File',
    EmptyMnemonic: 'Mnemonics cannot be empty',
    InvalidMnemonic: 'Invalid Mnemonics ',
    WalletRestoreFailed:'Wallet restore failed',
    ImportError: 'Your mnemonic is incorrect please check it carefully',
  },
  ConnectionInvitation:{
    VerifyMessage: 'Verify connection details carefully',
    ConsentMessage: 'New Connection Request',
  },
  ContactDetails: {
    Created: 'Created',
    ConnectionState: 'Connection State',
    AContact: 'A contact',
    DeleteConnection: 'Delete Connection',
    DeleteConnectionAlert: 'Are you sure you want to delete this connection?',
    DeleteConnectionSuccess: 'Connection deleted successfully',
    DeleteConnectionFailed: 'Failed to delete connection',
    ConnectionCannotDelete: 'Mediator connection cannot be deleted',
  },
  Credentials: {
    CredentialsNotFound: 'Credentials not found',
  },
  CredentialDetails: {
    Id: 'Id:',
    CreatedAt: 'Created At:',
    Version: 'Version',
    Issued: 'Issued',
    RemoveFromWallet: 'Remove from wallet',
  },
  CredentialOffer: {
    ThisIsTakingLongerThanExpected: 'This is taking longer than expected. Check back later for a new credential.',
    RejectThisCredential: 'Reject this Credential?',
    AcceptingCredential: 'Accepting Credential',
    SuccessfullyAcceptedCredential: 'Successfully accepted the Credential',
    RejectingCredential:'Rejecting Credential',
    SuccessfullyRejectedCredential:'Successfully rejected the Credential',
    CredentialNotFound: 'Credential not found',
    CredentialAccepted: 'Credential Accepted',
    CredentialRejected: 'Credential Rejected',
    CredentialAddedToYourWallet: 'Credential added to the wallet',
    CredentialDeclined: 'Credential declined',
    CredentialOnTheWay: 'The credential is on the way',
    CredentialOffer: 'New Credential Offer',
    IsOfferingYouACredential: 'is offering a credential',
  },
  TabStack: {
    Home: 'Home',
    Connections: 'Connection',
    Scan: 'Scan',
    Credentials: 'Credential',
    Settings: 'Settings',
  },
  Toasts:{
    Success: 'Success',
    Error: 'Error',
    Info: 'Info',
    Warning: 'Warning',
  },
  ProofRequest: {
    Title: '<b>{{connection}}</b> is requesting a verification from the Wallet. \n\nThey are asking to share:',
    OfferDelay: 'Offer delay',
    RejectThisProof: 'Reject this Proof?',
    AcceptingProof: 'Accepting Proof',
    SuccessfullyAcceptedProof: 'Successfully Accepted Proof',
    ProofNotFound: 'Proof not Found',
    RejectingProof: 'Rejecting Proof',
    ProofAccepted: 'Proof Accepted',
    ProofRejected: 'Proof Rejected',
    RequestedCredentialsCouldNotBeFound: 'Requested credentials could not be found',
    ProofRequest: 'New Proof Request',
    NotAvailableInYourWallet: 'Not available in the wallet',
    IsRequestng: 'is requesting',
    IsRequestingSomethingYouDontHaveAvailable: 'is requesting something not available in wallet',
    IsRequestingYouToShare: 'is requesting to share',
    WhichYouCanProvideFrom: 'which can be provided from',
    Details: 'Details',
    SendingTheInformationSecurely: 'Sending the information securely',
    InformationSentSuccessfully: 'Information sent successfully',
    ProofRequestDeclined: 'Proof request declined',
    ProofUpdateErrorTitle: 'Unable to update retrieved credentials',
    ProofUpdateErrorMessage: 'There was a problem while updating retrieved credentials',
    ProofAcceptErrorTitle: 'Unable to accept proof request',
    ProofAcceptErrorMessage: 'There was a problem while accepting the proof request',
    ProofRejectErrorTitle: 'Unable to reject the proof request',
    ProofRejectErrorMessage: 'There was a problem while rejecting the proof request',
    MissingInformation: {
      Title: 'The request cannot be completed',
      AlertMissingInformation: {
        Title: 'The wallet is missing information',
      },
    },
    ProofRequestParamsError:'ProofRequest route prams were not set properly',
    FetchProofError:'Unable to fetch proof from AFJ',
  },
  Record: {
    Hide: 'Hide',
    Show: 'Show',
    HideAll: 'Hide all',
    Hidden: 'Hidden',
  },
  QRScanner: {
    PermissionToUseCamera: 'Permission To Use Camera',
    PermissionMessage: 'We need your permission to use your camera',
    ScanMessage: 'Scan to connect',
    VerifyMessage: 'Only scan trustworthy sources and verify connection details carefully',
    NotAValidURL: 'URL non valid',
    NotBlankURL: 'Please enter URL',
    InvalidQrCode: 'Invalid QrCode',
  },
  Onboarding: {
    Slide1Title: 'Credentials List',
    Slide1Text: 'Get the list of issued credentials',
    Slide2Title: 'Scan to connect',
    Slide2Text: 'Scan QR to connect to organizations',
    Slide3Title: 'Secure Storage',
    Slide3Text: 'Store your credentials securely in wallet',
  },
  ScreenTitles: {
    Onboarding: 'App Introduction',
    LegalAndPrivacy: 'Legal & Privacy',
    CreatePin: 'PIN setup',
    Biometric: 'Biometric',
    Initialization: 'Initialize Wallet',
    SetupDelay: 'Initializing Wallet',
    WalletInitialized: 'Wallet Initialized',
    EnterPin: 'Login',
    ListContacts: 'Connections',
    Home: 'Start',
    Notifications: 'Notifications',
    ChangePin: 'Change PIN',
    Credentials: 'Credentials',
    CredentialDetails: 'Credential Details',
    Settings: 'Settings',
    CredentialOffer: 'Credential Offer',
    ProofRequest: 'Proof Request',
    Language: 'Language',
    ExportWallet: 'Export Wallet',
    ImportWallet: 'Import Wallet',
    ContactDetails: 'Connection Details',
    ViewMnemonic: 'View Mnemonic',
  },
  SearchBar: {
    placeholder: 'Search',
  },
};
export default translation;
