// prettier-ignore
const translation = {
  "Global": {
    "EnterPin": "Enter PIN",
    "EnterNewPin": "Enter New PIN",
    "6DigitPin": "6 Digit PIN",
    "Submit": "Submit",
    "NoneYet!": "None yet!",
    "Cancel": "Cancel",
    "Confirm": "Confirm",
    "Accept": "Accept",
    "Reject": "Reject",
    "Share": "Share",
    "Decline": "Decline",
    "ChangeEmail": "Change Email",
    "Back": "Back",
    "Next": "Next",
    "Continue": "Continue",
    "Info": "Information",
    "Failure": "Failure",
    "Success": "Success",
    "SomethingWentWrong": "Something went wrong",
    "Done": "Done",
    "Skip": "Skip",
    "Previous": "Prev",
    "View": "View",
    "Home": "Home",
    "ErrorCode": "Error Code",
    "Okay": "Okay",
    "Email": "Enter Email",
    "Verify": 'Verify',
    "Otp": 'Enter OTP',
    "ForgotPin": 'Forgot Pin',
    "ChangePin": 'Change Pin',
    "OldPin": 'Enter Old Pin',
    "Copy": 'Copy',
    "from": 'from',
    "ThisDecisionCannotBeChanged.": "This decision cannot be changed.",
    "ZeroRecords": 'No records available',
    "ImportWallet": "Import Wallet",
    "UserInactivity": "Logging out due to inactivity",
  },
  "Language": {
    "English": "English",
    "French": "French",  
    "German": "German",    
  },
  "Registration":{
    "UserAuthenticationEmail": "User authentication email",
    "EnterEmail": 'Please enter email',
    "ValidEmail": "Please enter a valid email address",
    'ResendOtp': 'Resend OTP',
    "RegisterAgain": "Please register again",
    "MnemonicMsg": "This phrase is the only way to export and import wallet, save it somewhere safe and secret. The phrase can be later found under the settings tab.",
    "Passphrase": "Passphrase",
    "Mnemonic": "Mnemonic",
    "SecondCounter": 'Seconds Left',
    "EmailInfo": 'Please enter a valid email address',
    "OtpInfo": 'Enter the OTP sent on entered email address',
    'OtpInvalid': 'Please enter the valid OTP',
    'OtpSuccess': 'OTP verified successfully',
    'WalletInitialized':'Wallet initialized successfully.',
  },
  "Terms": {
    "AcceptTerms": "Please read and agree to the terms and conditions below before using this application.",
    "TermsAndConditions": "These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service. Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.",
    "Attestation": "I, have read, understand and accept the terms and conditions.",
  },
  "PinCreate": {
    "UserAuthenticationPin": "User authentication pin",
    "PinMustBe6DigitsInLength": "PIN must be 6 digits in length",
    "ReEnterPinMustBe6DigitsInLength": 'Insufficient PIN length',
    "PinsEnteredDoNotMatch": "Pin entered does not match", 
    "PinsSuccess": "PIN created successfully", 
    "PinChange": "PIN changed successfully",
    "NewPinMatchwithOld": 'New Pin is same as the Old Pin',       
    "6DigitPin": "6 Digit PIN",
    "ReenterPin": "Re-Enter PIN",
    "ReenterNewPin": "Re-Enter the New PIN",
    "Create": "Create",
    "ValidOldPin": "Please enter valid Old PIN",
    "WalletCreated": "The wallet is created successfully.",
    "OR": "OR",
    "EmailConfirmation": "Warning",
    "CheckEmail": "Email should be the same as used for exporting the wallet.",
    "PinInfo": 'This pin is used for login'
  },
  "Biometric": {
    "Biometric": "Biometric",	
    "BiometricConfirm": "Confirm fingerprint",	
    "BiometricSuccess": "Fingerprint configured successfully",	
    "BiometricFailed": "Biometrics failed",	
    "BiometricCancel": "User cancelled the biometric prompt",	
    "BiometricNotSupport": "Biometrics not supported",	
    "RegisterPinandBiometric": 'Register PIN and Biometric',	
    "BiometricInfo": 'Register Biometric use for login'	
  },
  "Initialization":{
    "CompleteInitialization":"Complete the initialization",	
    "InitializationInfo":"Initialize new wallet or import old wallet",	
  },
  "Mnemonic":{
    "MnemonicTitle":"Below is the mnemonic for future references"	
  },
  "Home": {
    "Welcome": "Welcome",
    "Notifications": "Notifications",
    "NoNewUpdates": "There is no new notification.",	
    "NoCredentials": "There are no credentials in the wallet.",	
    "SeeAll": "See all",
    "YouHave": "You have",
    "Credential": "credential",
    "Credentials": "credentials",
    "InYourWallet": "in your wallet",
    "CredentialCountUndefinedError":"Credential count cannot be undefined",
  },
  "PinEnter": {
    "IncorrectPin": "Incorrect PIN", 
  }, 
  "Settings": {
    "ChangePin": 'Change Pin',
    "Version": "Version",
    "AppPreferences": "App Preferences",
    "AboutApp": "About App",
    "Language": "Language",
    "Logout": "Logout",
    "LogoutMsg": "Please confirm to logout",	
    "EnterMnemonic": 'Enter Mnemonic',
    "ValidMnemonic": 'Valid Mnemonic',
    "InvalidMnemonic": 'Invalid Mnemonic',
    "MnemonicMsg": 'Mnemonic can not be blank',
    "Yes": "Yes",
    "No": 'No',
    "ExportWallet": "Export Wallet",
    "ViewMnemonic": 'View Mnemonic',
  },
  "ExportWallet":{
    "WalletExportedPath": "Wallet Exported to the path:"
  },
  "ImportWallet":{
    "SelectWalletFile": "Select Wallet File",
    "EmptyMnemonic": 'Mnemonics cannot be empty',
    "InvalidMnemonic": 'Invalid Mnemonics ',
    "WalletRestoreFailed":"Wallet restore failed",
    "ImportError": "Either your email or mnemonic is incorrect please check it carefully",
  },
  "ConnectionInvitation":{
    "ConsentMessage": "New Connection Request"
  },
  "ContactDetails": {
    "Created": "Created",
    "ConnectionState": "Connection State",
    "AContact": "A contact",
    "DeleteConnection": "Delete Connection",
    "DeleteConnectionAlert": "Are you sure you want to delete this connection?",
    "DeleteConnectionSuccess": "Connection deleted successfully",
    "DeleteConnectionFailed": "Failed to delete connection",
    "ConnectionCannotDelete": "Mediator connection cannot be deleted",
  },
  "Credentials": {
    "CredentialsNotFound": "Credentials not found",
  },
  "CredentialDetails": {
    "Id": "Id:",
    "CreatedAt": "Created At:",
    "Version": "Version",
    "Issued": "Issued",
    "PrivacyPolicy": "Privacy policy",
    "TermsAndConditions": "Terms and conditions",
    "RemoveFromWallet": "Remove from wallet",
  },
  "CredentialOffer": {
    "ThisIsTakingLongerThanExpected": "This is taking longer than expected. Check back later for a new credential.",
    "RejectThisCredential?": "Reject this Credential?",
    "AcceptingCredential": "Accepting Credential",
    "SuccessfullyAcceptedCredential": "Successfully accepted the Credential",
    "RejectingCredential":"Rejecting Credential",
    "SuccessfullyRejectedCredential":"Successfully rejected the Credential",
    "CredentialNotFound": "Credential not found",
    "CredentialAccepted": "Credential Accepted",
    "CredentialRejected": "Credential Rejected",
    "CredentialAddedToYourWallet": "Credential added to the wallet",
    "CredentialDeclined": "Credential declined",
    "CredentialOnTheWay": "The credential is on the way",
    "CredentialOffer": "New Credential Offer",
    "IsOfferingYouACredential": "is offering a credential"
  },
  "TabStack": {
    "Home": "Home",
    "Connections": "Connection",
    "Scan": "Scan",
    "Credentials": "Credential",
    "Settings": "Settings",
  },
  "Toasts":{
    "Success": "Success",
    "Error": "Error",
    "Info": "Info",
    "Warning": "Warning",
  },
  "ProofRequest": {
    "Title": "<b>{{connection}}</b> is requesting a verification from the Wallet. \n\nThey are asking to share:",
    "OfferDelay": "Offer delay",
    "RejectThisProof?": "Reject this Proof?",
    "AcceptingProof": "Accepting Proof",
    "SuccessfullyAcceptedProof": "Successfully Accepted Proof",
    "ProofNotFound": "Proof not Found",
    "RejectingProof": "Rejecting Proof",
    "ProofAccepted": "Proof Accepted",
    "ProofRejected": "Proof Rejected",
    "RequestedCredentialsCouldNotBeFound": "Requested credentials could not be found",
    "ProofRequest": "New Proof Request",
    "NotAvailableInYourWallet": "Not available in the wallet",
    "IsRequestng": "is requesting",
    "IsRequestingSomethingYouDontHaveAvailable": "is requesting something not available in wallet",
    "IsRequestingYouToShare": "is requesting to share",
    "WhichYouCanProvideFrom": "which can be provided from",
    "Details": "Details",
    "SendingTheInformationSecurely": "Sending the information securely",
    "InformationSentSuccessfully": "Information sent successfully",
    "ProofRequestDeclined": "Proof request declined",
    "ProofUpdateErrorTitle": "Unable to update retrieved credentials",
    "ProofUpdateErrorMessage": "There was a problem while updating retrieved credentials",
    "ProofAcceptErrorTitle": "Unable to accept proof request",
    "ProofAcceptErrorMessage": "There was a problem while accepting the proof request",
    "ProofRejectErrorTitle": "Unable to reject the proof request",
    "ProofRejectErrorMessage": "There was a problem while rejecting the proof request",
    "MissingInformation": {
      "Title": "The request cannot be completed",
      "AlertMissingInformation": {
        "Title": "The wallet is missing information",
      },
    },
    "ProofRequestParamsError":"ProofRequest route prams were not set properly",
    "FetchProofError":"Unable to fetch proof from AFJ",
  },
  "Record": {
    "Hide": "Hide",
    "Show": "Show",
    "HideAll": "Hide all",
    "Hidden": "Hidden",
  },
  "QRScanner":{
    "PermissionToUseCamera":"Permission To Use Camera",
    "PermissionMessage":"We need your permission to use your camera",
    "NotAValidURL":"URL non valide",
    "InvalidQrCode":"Invalid QrCode",
  },
}
export default translation
