// prettier-ignore
const translation = {
  'Global': {
    'EnterPin': 'Pin eingeben',
    'EnterNewPin': 'Neue PIN eingeben',
    '6DigitPin': '6-stellige Pin',
    'Submit': 'Senden',
    'NoneYet!': 'Noch keine!',
    'Cancel': 'Abbrechen',
    'Confirm': 'Bestätigen',
    'Accept': 'Akzeptieren',
    'Reject': 'Zurückweisen',
    'Share': 'Teilen',
    'Decline': 'Ablehnen',
    'Back': 'Zurück',
    'Next': 'Weiter',
    'Continue': 'Weiter',
    'Info': 'Informationen',
    'Failure': 'Fehler',
    'Success': 'Erfolg',
    'SomethingWentWrong': 'Etwas ging schief',
    'Done': 'Erledigt',
    'Skip': 'Überspringen',
    'Previous': 'Vorher',
    'View': 'Ansicht',
    'Home': 'Startseite',
    'ErrorCode': 'Fehlercode',
    'Okay': 'OK',
    'Verify': 'Verifizieren',
    'ChangePin': 'PIN ändern',
    'OldPin': 'Alte PIN eingeben',
    'Copy': 'Kopieren',
    'from': 'von',
    'ThisDecisionCannotBeChanged.': 'Nicht änderbar.',
    'ZeroRecords': 'Keine Datensätze verfügbar.',
    'ImportWallet': 'Wallet importieren.',
    'WalletInitialized':'Ihre Brieftasche wurde erfolgreich initialisiert',
    'UserInactivity': 'Abgemeldet aufgrund von Inaktivität',
  },
  'Language': {
    'English': 'Englisch',
    'French': 'Französisch',
    'German': 'Deutsch',
  },
  'Registration':{
    'RegisterAgain': 'Bitte registrieren Sie sich erneut',
    'MnemonicMsg': 'Dieser individuelle Merksatz  ist die einzige Möglichkeit, Ihr Wallet zu exportieren und auf einem neuen Gerät zu importieren. Bitte bewahren Sie ihn daher an einem sicheren und geheimen Ort auf. Der Merksatz  ist für Sie auch später noch unter dem Menüpunkt «Einstellungen» zu finden.',
    'Passphrase': 'Passphrase',
    'Mnemonic': 'Merksatz',
    'SecondCounter': 'Verbleibende Sekunden',
    'WalletInitialized':'Wallet erfolgreich initialisiert.',
  },
  'Terms': {
    'AcceptTerms': 'This software is licensed as open source software under the <apachelink>Apache License Version 2.0</apachelink> and is governed by a firm commitment to your privacy and personal data, as explained in detail in our <privacylink>Privacy Policy</privacylink>.',
    'AcceptTermsContinue': 'Please only continue, in case you have noted and accepted the indicated documents.',
  },
  'PinCreate': {
    'UserAuthenticationPin': 'PIN',
    'PinMustBe6DigitsInLength': 'Die PIN muss 6 Ziffern lang sein',
    'ReEnterPinMustBe6DigitsInLength': 'Unzureichende PIN-Länge',
    'PinsEnteredDoNotMatch': 'Die eingegebenen PINs stimmen nicht überein',
    'PinsSuccess': 'PIN erfolgreich erstellt',
    'PinChange': 'PIN-Änderung erfolgreich',
    'NewPinMatchwithOld': 'Die neue PIN ist dieselbe wie die alte',
    '6DigitPin': '6-stellige PIN',
    'ReenterPin': 'PIN erneut eingeben',
    'ReenterNewPin': 'Geben Sie die neue PIN nochmals ein',
    'Create': 'Erstellen',
    'ValidOldPin': 'Bitte geben Sie eine gültige alte PIN ein',
    'WalletCreated': 'Das Wallet wurde erfolgreich erstellt',
    'OR': 'oder',
    'PinInfo': 'Diese PIN wird für zum Öffnen der Wallet verwendet',
  },
  'Biometric': {
    'Biometric': 'Biometrisch',
    'BiometricConfirm': 'Fingerabdruck bestätigen',
    'BiometricSuccess': 'Fingerabdruck erfolgreich hinterlegt',
    'BiometricFailed': 'Biometrie ist fehlgeschlagen',
    'BiometricCancel': 'Sie haben die biometrische Eingabeaufforderung abgebrochen',
    'BiometricNotSupport': 'Biometrische Daten werden nicht unterstützt',
    'RegisterPinandBiometric': 'Registrieren Sie PIN und Biometrie',
    'BiometricInfo': 'Registrieren Sie Ihre biometrischen Daten für die Anmeldung',
  },
  'Initialization':{
    'CompleteInitialization':'Schliessen Sie die Initialisierung ab',
    'InitializationInfo':"Erstellen Sie ein neues oder importieren Sie ein bereits vorhandenes Wallet",
  },
  'Mnemonic':{
    'MnemonicTitle':'Unten finden Sie Ihren Merksatz für zukünftige Sicherheitsabfragen',
  },
  'Home': {
    'Welcome': 'Herzlich willkommen',
    'Notifications': 'Benachrichtigungen',
    'NoNewUpdates': 'Es gibt keine neue Benachrichtigung.',
    'NoCredentials': 'Es gibt keine Zugangsdaten in der Wallet.',
    'SeeAll': 'Alle anzeigen',
    'YouHave': 'Sie haben',
    'Credential': 'Zugangsdaten',
    'Credentials': 'Zugangsdaten',
    'InYourWallet': 'in Ihrem Wallet',
    'CredentialCountUndefinedError':'Credential count cannot be undefined',
  },
  'PinEnter': {
    'IncorrectPin': 'Falsche PIN',
  },
  'Settings': {
    'ChangePin': 'Pin ändern',
    'Version': 'Version',
    'AppPreferences': 'App-Einstellungen',
    'AboutApp': 'Über App',
    'Language': 'Sprache',
    'Logout': 'Ausloggen',
    'LogoutMsg': 'Bitte bestätigen Sie die Abmeldung',
    'MnemonicMsg': 'Mnemonik darf nicht leer sein',
    'EnterMnemonic': 'Geben Sie Mnemonik ein',
    'ValidMnemonic': 'Gültige Mnemonik',
    'InvalidMnemonic': 'Ungültige Mnemonik',
    'LegalAndPrivacy': 'Legal & Privacy',
    'Yes': 'Jawohl',
    'No': 'Nein',
    'ExportWallet': 'Brieftasche exportieren',
    'ViewMnemonic': 'Mnemonik ansehen',
  },
  'ExportWallet':{
    'WalletExportedPath': 'Das Wallet wurde unter dem folgenden Pfad exportiert:',
  },
  'ImportWallet':{
    'SelectWalletFile': 'Wählen Sie eine Wallet-Datei aus',
    'EmptyMnemonic': 'Der persönliche Merksatz darf nicht leer sein.',
    'InvalidMnemonic': 'Merksatz nicht korrekt',
    'WalletRestoreFailed':'Die Wiederherstellung des Wallets ist fehlgeschlagen',
    'ImportError': 'Entweder Ihre E-Mail oder der Merksatz ist falsch, bitte überprüfen Sie beide sorgfältig',
  },
  'ConnectionInvitation':{
    'VerifyMessage': 'Bitte überprüfen Sie die angegebenen Verbindungsdetails sorgfältig',
    'ConsentMessage': 'Neue Verbindungsanforderung',
  },
  'ContactDetails': {
    'Created': 'Erstellt',
    'ConnectionState': 'Verbindungsstatus',
    'AContact': 'Ein Kontakt',
    'DeleteConnection': 'Verbindung löschen',
    'DeleteConnectionAlert': 'Möchten Sie diese Verbindung wirklich löschen?',
    'DeleteConnectionSuccess': 'Verbindung erfolgreich gelöscht',
    'DeleteConnectionFailed': 'Fehler beim Löschen der Verbindung',
    'ConnectionCannotDelete': 'Mediator-Verbindung kann nicht gelöscht werden',
  },
  'Credentials': {
    'CredentialsNotFound': 'Credential nicht gefunden',
  },
  'CredentialDetails': {
    'Id': 'Id:',
    'CreatedAt': 'Erzeugt:',
    'Version': 'Version',
    'Issued': 'Ausgestellt',
    'RemoveFromWallet': 'Aus dem Wallet entfernen',
  },
  'CredentialOffer': {
    'ThisIsTakingLongerThanExpected': 'Dies dauert länger als erwartet. Bitte versuchen Sie es später noch einmal.',
    'RejectThisCredential?': 'Diesen Credential ablehnen?',
    'AcceptingCredential': 'Akzeptieren des Credential',
    'SuccessfullyAcceptedCredential': 'Credential erfolgreich akzeptiert',
    'RejectingCredential':'Credential ablehnen',
    'SuccessfullyRejectedCredential':'Credential wurde erfolgreich abgelehnt',
    'CredentialNotFound': 'Credential nicht gefunden',
    'CredentialAccepted': 'Credential akzeptiert',
    'CredentialRejected': 'Credential abgelehnt',
    'CredentialAddedToYourWallet': 'Das Credential wurde zur Wallet hinzugefügt',
    'CredentialDeclined': 'Credential abgelehnt',
    'CredentialOnTheWay': 'Credential wird vorbereitet',
    'CredentialOffer': 'Neuer Credential',
    'IsOfferingYouACredential': 'bietet einen Credential an',
  },
  'TabStack': {
    'Home': 'Zuhause',
    'Connections': 'Verbindung',
    'Scan': 'Scan',
    'Credentials': 'Credentials',
    'Settings': 'Einstellungen',
  },
  'Toasts':{
    'Success': 'Erfolg',
    'Error': 'Fehler',
    'Info': 'Information',
    'Warning': 'Warnung',
  },
  'ProofRequest': {
    'Title': '<b>{{connection}}</b> bittet Sie um einen Nachweis :',
    'OfferDelay': 'Verzögerung',
    'RejectThisProof?': 'Diesen Nachweis ablehnen?',
    'AcceptingProof': 'Nachweis wird akzeptiert',
    'SuccessfullyAcceptedProof': 'Nachweis erfolgreich akzeptiert',
    'ProofNotFound': 'Nachweis nicht gefunden',
    'RejectingProof': 'Nachweis wird abgelehnt',
    'ProofAccepted': 'Nachweis akzeptiert',
    'ProofRejected': 'Nachweis abgelehnt',
    'RequestedCredentialsCouldNotBeFound': 'Angeforderter Credential konnte nicht gefunden werden',
    'ProofRequest': 'Neuer Nachweis angefordert',
    'NotAvailableInYourWallet': 'Credential nicht im Wallet verfübar',
    'IsRequestng': 'Diesen Nachweis ablehnen?1',
    'IsRequestingSomethingYouDontHaveAvailable': 'fordert etwas an, das nicht im Wallet verfügbar ist?2',
    'IsRequestingYouToShare': 'bittet um Freigabe?3',
    'WhichYouCanProvideFrom': 'kann bereit gestellt werden von?4',
    'Details': 'Diesen Nachweis ablehnen?5',
    'SendingTheInformationSecurely': 'Informationen gesichert versenden?6',
    'InformationSentSuccessfully': 'Die Informationen wurden gesichert übertragen.7',
    'ProofRequestDeclined': 'Diesen Nachweis ablehnen?8',
    'ProofUpdateErrorTitle': 'Ausgewählte Credentials können nicht aktualisiert werden',
    'ProofUpdateErrorMessage': 'Beim Aktualisieren der ausgewählten Credentials ist ein Problem aufgetreten',
    'ProofAcceptErrorTitle': 'Credential kann nicht angenommen werden',
    'ProofAcceptErrorMessage': 'Beim Akzeptieren des Credentials ist ein Problem aufgetreten',
    'ProofRejectErrorTitle': 'Der Credential kann nicht abgelehnt werden',
    'ProofRejectErrorMessage': 'Beim Ablehnen der Nachweisanforderung ist ein Problem aufgetreten',
    'MissingInformation': {
      'Title': 'Die Anfrage kann nicht abgeschlossen werden',
      'AlertMissingInformation': {
        'Title': 'Der Wallet fehlen notwendige Informationen',
      },
    },
    'ProofRequestParamsError':'Die Nachweisanforderungen wurde nicht korrekt konfiguriert',
    'FetchProofError':'Nachweis von AFJ konnte nicht abgerufen werden',
  },
  'Record': {
    'Hide': 'Ausblenden',
    'Show': 'Zeigen',
    'HideAll': 'Alles ausblenden',
    'Hidden': 'Ausgeblendet',
  },
  'QRScanner':{
    'PermissionToUseCamera':'Erlaubnis zur Verwendung der Kamera',
    'PermissionMessage':'Die App benötigt Ihre Erlaubnis, die Kamera zu verwenden',
    'ScanMessage': 'Zum Verbinden scannen',
    'VerifyMessage':'Scannen Sie nur vertrauenswürdige Quellen und überprüfen Sie die Verbindungsdetails sorgfältig',
    'NotAValidURL':'Die URL ist fehlerhaft',
    'NotBlankURL': 'Bitte URL eingeben',
    'InvalidQrCode':'Der QR-Code ist ungültig',
  },
};
export default translation;
