// prettier-ignore
const translation = {
  'Global': {
    'EnterPin': 'Pin eingeben',
    'EnterNewPin': 'Neue PIN eingeben',
    '6DigitPin': '6-stellige Pin',
    'Submit': 'Senden',
    'NoneYet!': 'Noch keine!',
    'Cancel': 'Abbrechen',
    'Confirm': 'Bestätigen Sie',
    'Accept': 'Akzeptieren',
    'Reject': 'Ablehnen',
    'Share': 'Teilen',
    'Decline': 'Ablehnen',
    'Back': 'Zurück',
    'Next': 'Weiter',
    'Continue': 'Weiter',
    'Info': 'Informationen',
    'Failure': 'Scheitern',
    'Success': 'Erfolg',
    'SomethingWentWrong': 'Etwas ging schief',
    'Done': 'Erledigt',
    'Skip': 'Überspringen',
    'Previous': 'Vorher',
    'View': 'Ansicht',
    'Home': 'Startseite',
    'ErrorCode': 'Fehlercode',
    'Okay': 'Okay',
    'Verify': 'Verifizieren',
    'ChangePin': 'PIN ändern',
    'OldPin': 'Alte PIN eingeben',
    'Copy': 'Kopieren',
    'from': 'von',
    'ThisDecisionCannotBeChanged.': 'Diese Entscheidung kann nicht geändert werden.',
    'ZeroRecords': 'Keine Aufzeichnungen verfügbar',
    'ImportWallet': 'Brieftasche importieren',
    'WalletInitialized':'Ihre Brieftasche wurde erfolgreich initialisiert',
    'UserInactivity': 'Abmelden aufgrund von Inaktivität',
  },
  'Language': {
    'English': 'Englisch',
    'French': 'Französisch',
    'German': 'Deutsch',
  },
  'Terms': {
    'AcceptTerms': 'Bitte lesen und akzeptieren Sie die nachstehenden Bedingungen, bevor Sie diese Anwendung verwenden.',
    'TermsAndConditions': 'Diese Bedingungen legen die Rechte und Pflichten aller Nutzer in Bezug auf die Nutzung des Dienstes fest. Ihr Zugang zu und Ihre Nutzung des Dienstes setzt voraus, dass Sie diese Bedingungen akzeptieren und einhalten. Diese Allgemeinen Geschäftsbedingungen gelten für alle Besucher, Benutzer und andere, die auf den Dienst zugreifen oder ihn nutzen.',
    'Attestation': 'Ich habe die AGB gelesen, verstanden und akzeptiere sie.',
  },
  'Registration':{
    'RegisterAgain': 'Bitte registrieren Sie sich erneut',
    'MnemonicMsg': 'Dieser Satz ist die einzige Möglichkeit, Brieftaschen zu exportieren und zu importieren und an einem sicheren und geheimen Ort aufzubewahren.Die Phrase kann später unter der Registerkarte Einstellungen gefunden werden',
    'Passphrase': 'Passphrase',
    'Mnemonic': 'Mnemonik',
    'SecondCounter': 'Zweite links',
    'WalletInitialized':'Wallet erfolgreich initialisiert.',
  },
  'PinCreate': {
    'UserAuthenticationPin': 'Benutzerauthentifizierungs-PIN',
    'PinMustBe6DigitsInLength': 'Die PIN muss 6 Ziffern lang sein',
    'ReEnterPinMustBe6DigitsInLength': 'Unzureichende PIN-Länge',
    'PinsEnteredDoNotMatch': 'Die eingegebenen Pins stimmen nicht überein',
    'PinsSuccess': 'Pin erfolgreich erstellt',
    'PinChange': 'PIN-Änderung erfolgreich',
    'NewPinMatchwithOld': 'Der neue Pin ist derselbe wie der alte Pin',
    '6DigitPin': '6-stellige PIN',
    'ReenterPin': 'PIN erneut eingeben',
    'ReenterNewPin': 'Geben Sie die neue PIN erneut ein',
    'Create': 'Schaffen',
    'ValidOldPin': 'Bitte geben Sie eine gültige alte PIN ein',
    'WalletCreated': 'Die Brieftasche wurde erfolgreich erstellt',
    'OR': 'ODER',
    'PinInfo': 'Dieser Pin wird für die Anmeldung verwendet',
  },
  'Biometric': {
    'Biometric': 'Biometrisch',
    'BiometricConfirm': 'Confirm fingerprint',
    'BiometricSuccess': 'Fingerabdruck erfolgreich konfiguriert',
    'BiometricFailed': 'Biometrie fehlgeschlagen',
    'BiometricCancel': 'Der Benutzer hat die biometrische Eingabeaufforderung abgebrochen',
    'BiometricNotSupport': 'Biometrische Daten werden nicht unterstützt',
    'RegisterPinandBiometric': 'Registrieren Sie PIN und Biometrie',
    'BiometricInfo': 'Registrieren Sie die biometrische Verwendung für die Anmeldung',
  },
  'Initialization':{
    'CompleteInitialization':'Schließen Sie die Initialisierung ab',
    'InitializationInfo':"Initialiser le nouveau portefeuille ou importer l'ancien portefeuille",
  },
  'Mnemonic':{
    'MnemonicTitle':'Unten ist die Mnemonik für zukünftige Referenzen',
  },
  'Home': {
    'Welcome': 'Herzlich willkommen',
    'Notifications': 'Benachrichtigungen',
    'NoNewUpdates': 'Es gibt keine neue Benachrichtigung.',
    'NoCredentials': 'Es gibt keine Zugangsdaten in der Wallet.',
    'SeeAll': 'Alle anzeigen',
    'YouHave': 'Sie haben',
    'Credential': 'Zugangsdaten',
    'Credentials': 'Zugangsdaten',
    'InYourWallet': 'in Ihrem Wallet',
  },
  'PinEnter': {
    'IncorrectPin': 'Falsche PIN',
  },
  'Settings': {
    'ChangePin': 'Pin ändern',
    'Version': 'Version',
    'AppPreferences': 'App-Einstellungen',
    'AboutApp': 'Über App',
    'Language': 'Sprache',
    'Logout': 'Ausloggen',
    'LogoutMsg': 'Bitte bestätigen Sie die Abmeldung',
    'MnemonicMsg': 'Mnemonik darf nicht leer sein',
    'EnterMnemonic': 'Geben Sie Mnemonik ein',
    'ValidMnemonic': 'Gültige Mnemonik',
    'InvalidMnemonic': 'Ungültige Mnemonik',
    'Yes': 'Jawohl',
    'No': 'Nein',
    'ExportWallet': 'Brieftasche exportieren',
    'ViewMnemonic': 'Mnemonik ansehen',
  },
  'ExportWallet':{
    'WalletExportedPath': 'Wallet in den Pfad exportiert :',
  },
  'ImportWallet':{
    'SelectWalletFile': 'Wählen Sie Wallet-Datei aus',
    'EmptyMnemonic': 'Mnemoniken dürfen nicht leer sein',
    'InvalidMnemonic': 'Ungültige Mnemonik ',
    'WalletRestoreFailed':'Wallet-Wiederherstellung fehlgeschlagen',
    'ImportError': 'Entweder Ihre E-Mail oder Mnemonik ist falsch, bitte überprüfen Sie es sorgfältig',
  },
  'ConnectionInvitation':{
    'VerifyMessage': 'Überprüfen Sie die Verbindungsdetails sorgfältig',
    'ConsentMessage': 'Neue Verbindungsanforderung',
  },
  'ContactDetails': {
    'Created': 'Erstellt',
    'ConnectionState': 'Verbindungs status',
    'AContact': 'Ein Kontakt',
    'DeleteConnection': 'Verbindung löschen',
    'DeleteConnectionAlert': 'Möchten Sie diese Verbindung wirklich löschen?',
    'DeleteConnectionSuccess': 'Verbindung erfolgreich gelöscht',
    'DeleteConnectionFailed': 'Fehler beim Löschen der Verbindung',
    'ConnectionCannotDelete': 'Mediator-Verbindung kann nicht gelöscht werden',
  },
  'Credentials': {
    'CredentialsNotFound': 'Anmeldedaten nicht gefunden',
  },
  'CredentialDetails': {
    'Id': 'Ausweis:',
    'CreatedAt': 'Hergestellt in:',
    'Version': 'Ausführung',
    'Issued': 'Problematisch',
    'PrivacyPolicy': 'Datenschutz-Bestimmungen',
    'TermsAndConditions': 'Geschäftsbedingungen',
    'RemoveFromWallet': 'Aus der Brieftasche entfernen',
  },
  'CredentialOffer': {
    'ThisIsTakingLongerThanExpected': 'Dies dauert länger als erwartet. Schauen Sie später noch einmal vorbei, um einen neuen Berechtigungsnachweis zu erhalten.',
    'RejectThisCredential?': 'Diese Anmeldeinformationen ablehnen?',
    'AcceptingCredential': 'Akzeptieren von Anmeldeinformationen',
    'SuccessfullyAcceptedCredential': 'Anmeldeinformationen erfolgreich akzeptiert',
    'RejectingCredential':'Ausweis ablehnen',
    'SuccessfullyRejectedCredential':'Die Anmeldeinformationen wurden erfolgreich abgelehnt',
    'CredentialNotFound': 'Anmeldedaten nicht gefunden',
    'CredentialAccepted': 'Anmeldeinformationen akzeptiert',
    'CredentialRejected': 'Anmeldeinformationen abgelehnt',
    'CredentialAddedToYourWallet': 'Der Brieftasche hinzugefügte Anmeldeinformationen',
    'CredentialDeclined': 'Anmeldedaten abgelehnt',
    'CredentialOnTheWay': 'Der Ausweis ist unterwegs',
    'CredentialOffer': 'Neue Anmeldeinformationen',
    'IsOfferingYouACredential': 'is offering a credential',
  },
  'TabStack': {
    'Home': 'Zuhause',
    'Connections': 'Verbindung',
    'Scan': 'Scan',
    'Credentials': 'Referenzen',
    'Settings': 'Einstellungen',
  },
  'ProofRequest': {
    'Title': '<b>{{connection}}</b> demande une vérification à partir de votre portefeuille. \n\nSie bitten darum, zu teilen :',
    'OfferDelay': 'Angebotsverzögerung',
    'RejectThisProof?': 'Diesen Nachweis ablehnen?',
    'AcceptingProof': 'Nachweis wird akzeptiert',
    'SuccessfullyAcceptedProof': 'Nachweis erfolgreich akzeptiert',
    'ProofNotFound': 'Nachweis nicht gefunden',
    'RejectingProof': 'Nachweis wird abgelehnt',
    'ProofAccepted': 'Nachweis akzeptiert',
    'ProofRejected': 'Nachweis abgelehnt',
    'RequestedCredentialsCouldNotBeFound': 'Angeforderte Anmeldeinformationen konnten nicht gefunden werden',
    'ProofRequest': 'Neuer Nachweis angefordert',
    'NotAvailableInYourWallet': 'Diesen Nachweis ablehnen?0',
    'IsRequestng': 'Diesen Nachweis ablehnen?1',
    'IsRequestingSomethingYouDontHaveAvailable': 'fordert etwas an, das nicht in der Brieftasche verfügbar ist?2',
    'IsRequestingYouToShare': 'bittet um Freigabe?3',
    'WhichYouCanProvideFrom': 'die bereitgestellt werden können?4',
    'Details': 'Diesen Nachweis ablehnen?5',
    'SendingTheInformationSecurely': 'Diesen Nachweis ablehnen?6',
    'InformationSentSuccessfully': 'Diesen Nachweis ablehnen?7',
    'ProofRequestDeclined': 'Diesen Nachweis ablehnen?8',
    'ProofUpdateErrorTitle': 'Abgerufene Anmeldeinformationen können nicht aktualisiert werden',
    'ProofUpdateErrorMessage': 'Beim Aktualisieren der abgerufenen Anmeldeinformationen ist ein Problem aufgetreten',
    'ProofAcceptErrorTitle': 'Nachweisanforderung kann nicht angenommen werden',
    'ProofAcceptErrorMessage': 'Beim Akzeptieren der Nachweisanforderung ist ein Problem aufgetreten',
    'ProofRejectErrorTitle': 'Die Nachweisanforderung kann nicht abgelehnt werden',
    'ProofRejectErrorMessage': 'Beim Ablehnen der Nachweisanforderung ist ein Problem aufgetreten',
    'MissingInformation': {
      'Title': 'Die Anfrage kann nicht abgeschlossen werden',
      'AlertMissingInformation': {
        'Title': 'Der Brieftasche fehlen Informationen',
      },
    },
    'ProofRequestParamsError':'ProofRequest-Routenkinderwagen wurden nicht richtig eingestellt',
    'FetchProofError':'Nachweis von AFJ konnte nicht abgerufen werden',
  },
  'Toasts':{
    'Success': 'Erfolg',
    'Error': 'Fehler',
    'Info': 'Die Info',
    'Warning': 'Warnung',
  },
  'Record': {
    'Hide': 'Ausblenden',
    'Show': 'Zeigen',
    'HideAll': 'Versteck alles',
    'Hidden': 'Versteckt',
  },
  'QRScanner':{
    'PermissionToUseCamera':'Erlaubnis zur Verwendung der Kamera',
    'PermissionMessage':'Wir benötigen Ihre Erlaubnis, Ihre Kamera zu verwenden',
    'ScanMessage': 'Zum Verbinden scannen',
    'VerifyMessage':'Scannen Sie nur vertrauenswürdige Quellen und überprüfen Sie die Verbindungsdetails sorgfältig',
    'NotAValidURL':'URL non valide',
    'NotBlankURL': 'Bitte URL eingeben',
    'InvalidQrCode':'QrCode invalide',
  },
};
export default translation;
