// prettier-ignore
const translation = {
  "Global": {
    "EnterPin": "Pin eingeben",
    "EnterNewPin": "Neue PIN eingeben",
    "6DigitPin": "6-stellige Pin",
    "Submit": "Senden",
    "NoneYet!": "Noch keine!",
    "Cancel": "Abbrechen",
    "Confirm": "Bestätigen Sie",
    "Accept": "Akzeptieren",
    "Reject": "Ablehnen",
    "Share": "Teilen",
    "Decline": "Ablehnen",
    "Back": "Zurück",
    "Next": "Weiter",
    "Continue": "Weiter",
    "Info": "Informationen",
    "Failure": "Scheitern",
    "Success": "Erfolg",
    "SomethingWentWrong": "Etwas ging schief",
    "Done": "Erledigt",
    "Skip": "Überspringen",
    "Previous": "Vorher",
    "View": "Ansicht",
    "Home": "Startseite",
    "ErrorCode": "Fehlercode",
    "Okay": "Okay",
    "Email": "E-Mail eingeben",
    "Verify": 'Verifizieren',
    "Otp": 'OTP eingeben',
    "ForgotPin": 'PIN vergessen',
    "ChangePin": 'PIN ändern',
    "OldPin": 'Alte PIN eingeben',
    "Copy": 'Kopieren',
    "from": 'von',
    "ThisDecisionCannotBeChanged.": "Diese Entscheidung kann nicht geändert werden.",
    "ZeroRecords": 'Keine Aufzeichnungen verfügbar',
  },
  "Language": {
    "English": "Englisch",
    "French": "Französisch",
    "German": "Deutsch"
  },
  "Terms": {
    "AcceptTerms": "Bitte stimmen Sie den nachstehenden Bedingungen zu, bevor Sie diese Anwendung nutzen.",
    "TermsAndConditions": "Diese Bedingungen legen die Rechte und Pflichten aller Nutzer in Bezug auf die Nutzung des Dienstes fest. Ihr Zugang zu und Ihre Nutzung des Dienstes setzt voraus, dass Sie diese Bedingungen akzeptieren und einhalten. Diese Allgemeinen Geschäftsbedingungen gelten für alle Besucher, Benutzer und andere, die auf den Dienst zugreifen oder ihn nutzen.",
    "Attestation": "Ich habe die Bedingungen gelesen, verstanden und akzeptiere sie."
  },
  "Registration":{
    "UserAuthenticationEmail": "E-Mail zur Benutzerauthentifizierung",
    "EnterEmail": 'Bitte E-Mail eingeben',
    "ValidEmail": "bitte eine gültige E-Mail-Adresse eintragen",
    'ResendOtp': 'OTP erneut senden',
    "RegisterAgain": "Sie müssen sich erneut registrieren",
    "MnemonicMsg": "Dies ist der Satz, der verwendet wird, um Ihren Wallet-Seed zu erstellen. Bitte speichern Sie ihn sicher",
    "Passphrase": "Passphrase"
  },
  "PinCreate": {
    "UserAuthenticationPin": "Benutzerauthentifizierungs-PIN",
    "PinMustBe6DigitsInLength": "Die PIN muss 6 Ziffern lang sein",
    "ReEnterPinMustBe6DigitsInLength": 'Le code PIN doit être composé de 6 chiffres',
    "PinsEnteredDoNotMatch": "Die eingegebenen Pins stimmen nicht überein", 
    "PinsSuccess": "Pin erfolgreich erstellt",    
    "6DigitPin": "6-stellige PIN",
    "ReenterPin": "PIN erneut eingeben",
    "ReenterNewPin": "Neue PIN erneut eingeben",
    "Create": "Schaffen",
    "ValidOldPin": "Bitte gültige alte PIN eingeben",
    "WalletCreated": "Ihre Brieftasche wurde erfolgreich erstellt."
  },
  "Biometric": {
    "Biometric": "Biometrisch",
    "BiometricConfirm": "Confirm fingerprint",
    "BiometricSuccess": "Fingerabdruck bestätigen",
    "BiometricFailed": "Biometrie fehlgeschlagen",
    "BiometricCancle": "Der Benutzer hat die biometrische Eingabeaufforderung abgebrochen",
    "BiometricNotSupport": "Biometrische Daten werden nicht unterstützt",
    "RegisterPinandBiometric": 'PIN und Biometrie registrieren'
  },
  "Home": {
    "Welcome": "Willkommen",
    "Notifications": "Benachrichtigungen",
    "NoNewUpdates": "Sie haben keine neuen Benachrichtigungen.",
    "NoCredentials": "Sie haben keine Zugangsdaten in Ihrem Wallet.",
    "SeeAll": "Alle anzeigen",
    "YouHave": "Sie haben",
    "Credential": "Zugangsdaten",
    "Credentials": "Zugangsdaten",
    "InYourWallet": "in Ihrem Wallet"
  },
  "PinEnter": {
    "IncorrectPin": "Falsche PIN", 
  }, 
  "Settings": {
    "ChangePin": "Pin ändern",
    "Version": "Version",
    "AppPreferences": "App-Einstellungen",
    "AboutApp": "Über App",
    "Language": "Sprache",
    "Logout": "Ausloggen",
    "LogoutMsg": "Möchten Sie sich wirklich abmelden",
    "Yes": "Jawohl",
    "No": 'Nein',
  },
  "ConnectionInvitation":{
    "ConsentMessage": "Neue Verbindungsanforderung"
  },
  "ContactDetails": {
    "Created": "Erstellt",
    "ConnectionState": "Verbindungs status",
    "AContact": "Ein Kontakt",
  },
  "Credentials": {
    "CredentialsNotFound": "Anmeldedaten nicht gefunden",
  },
  "CredentialDetails": {
    "Id": "Ausweis:",
    "CreatedAt": "Hergestellt in:",
    "Version": "Ausführung",
    "Issued": "Problematisch",
    "PrivacyPolicy": "Datenschutz-Bestimmungen",
    "TermsAndConditions": "Geschäftsbedingungen",
    "RemoveFromWallet": "Aus der Brieftasche entfernen",
  },
  "CredentialOffer": {
    "ThisIsTakingLongerThanExpected": "Dies dauert länger als erwartet. Schauen Sie später noch einmal nach, um Ihre neuen Anmeldeinformationen zu erhalten.",
    "RejectThisCredential?": "Diese Anmeldeinformationen ablehnen?",
    "AcceptingCredential": "Akzeptieren von Anmeldeinformationen",
    "SuccessfullyAcceptedCredential": "Anmeldeinformationen erfolgreich akzeptiert",
    "RejectingCredential":"Ausweis ablehnen",
    "SuccessfullyRejectedCredential":"Anmeldeinformationen erfolgreich abgelehnt",
    "CredentialNotFound": "Anmeldedaten nicht gefunden",
    "CredentialAccepted": "Anmeldeinformationen akzeptiert",
    "CredentialRejected": "Anmeldeinformationen abgelehnt",
    "CredentialAddedToYourWallet": "Zugangsdaten zu Ihrem Wallet hinzugefügt",
    "CredentialDeclined": "Anmeldedaten abgelehnt",
    "CredentialOnTheWay": "Ihr Ausweis ist unterwegs",
    "CredentialOffer": "Neue Anmeldeinformationen",
    "IsOfferingYouACredential": "bietet Ihnen einen Ausweis an"
  },
  "TabStack": {
    "Home": "Zuhause",
    "Connections": "Verbindung",
    "Scan": "Scan",
    "Credentials": "Referenzen",
    "Settings": "Einstellungen",
  },
  "ProofRequest": {
    "Title": "<b>{{connection}}</b> demande une vérification à partir de votre portefeuille. \n\nIls vous demandent de partager :",
    "OfferDelay": "Angebotsverzögerung",
    "RejectThisProof?": "Diesen Nachweis ablehnen?",
    "AcceptingProof": "Nachweis wird akzeptiert",
    "SuccessfullyAcceptedProof": "Nachweis erfolgreich akzeptiert",
    "ProofNotFound": "Nachweis nicht gefunden",
    "RejectingProof": "Nachweis wird abgelehnt",
    "ProofAccepted": "Nachweis akzeptiert",
    "ProofRejected": "Nachweis abgelehnt",
    "RequestedCredentialsCouldNotBeFound": "Angeforderte Anmeldeinformationen konnten nicht gefunden werden",
    "ProofRequest": "Neuer Nachweis angefordert",
    "NotAvailableInYourWallet": "Diesen Nachweis ablehnen?0",
    "IsRequestng": "Diesen Nachweis ablehnen?1",
    "IsRequestingSomethingYouDontHaveAvailable": "Diesen Nachweis ablehnen?2",
    "IsRequestingYouToShare": "Diesen Nachweis ablehnen?3",
    "WhichYouCanProvideFrom": "Diesen Nachweis ablehnen?4",
    "Details": "Diesen Nachweis ablehnen?5",
    "SendingTheInformationSecurely": "Diesen Nachweis ablehnen?6",
    "InformationSentSuccessfully": "Diesen Nachweis ablehnen?7",
    "ProofRequestDeclined": "Diesen Nachweis ablehnen?8",
    "MissingInformation": {
      "Title": "Die Anfrage kann nicht abgeschlossen werden",
      "AlertMissingInformation": {
        "Title": "In Ihrer Brieftasche fehlen Informationen"
      }
    }
  },
  "Toasts":{
    "Success": "Erfolg",
    "Error": "Fehler",
    "Info": "Die Info",
    "Warning": "Warnung",
  },
  "Record": {
    "Hide": "Ausblenden",
    "Show": "Zeigen",
    "HideAll": "Versteck alles",
    "Hidden": "Versteckt",
  }
}
export default translation
