// prettier-ignore
const translation = {
  "Global": {
    "EnterPin": "Entrer le code PIN",
    "EnterNewPin": "Entrez le nouveau NIP",
    "6DigitPin": "Pin à 6 chiffres",
    "Submit": "Soumettre",
    "NoneYet!": "Pas encore !",
    "Cancel": "Annuler",
    "Confirm": "Confirmer",
    "Accept": "Accepter",
    "Reject": "Rejeter",
    "Share": "Partager",
    "Decline": "Refuser",
    "Back": "Retour",
    "Next": "Suivant",
    "Continue": "Continuer",
    "Info": "Information",
    "Failure": "Échec",
    "Success": "Succès",
    "SomethingWentWrong": "Quelque chose s'est mal passé",
    "Done": "Terminé",
    "Skip": "Ignorer",
    "Previous": "Précédente",
    "View": "Voir",
    "Home": "Accueil",
    "ErrorCode": "Code d'erreur",
    "Okay": "Okay",
    "Email": "Entrez votre e-mail",
    "Verify": 'Vérifier',
    "Otp": 'Entrez OTP',
    "ForgotPin": 'Épingle oubliée',  
    "ChangePin": 'Changer dépingle',
    "OldPin": 'Saisir lancien code PIN',
    "Copy": 'Copie',
    "from": 'à partir de',
    "ThisDecisionCannotBeChanged.": "Cette décision ne peut être modifiée.",
    "ZeroRecords": 'Aucun enregistrement disponible',
    "ImportWallet": "Importer un portefeuille",
    'WalletInitialized':'Votre portefeuille a été initialisé avec succès.',

    "UserInactivity": "Déconnexion en raison de l'inactivité",
  },
  "Language": {
    "English": "Anglais",
    "French": "Français",
    "German": "Allemand"
  },
  "Registration":{
    "UserAuthenticationEmail": "Courriel d'authentification de l'utilisateur",
    "EnterEmail": 'Veuillez saisir un e-mail',
    "ValidEmail": "Veuillez saisir une adresse e-mail valide",
    'ResendOtp': 'Renvoyer OTP',
    "RegisterAgain": "Vous devez vous inscrire à nouveau",
    "MnemonicMsg": "Cette phrase est le seul moyen d'exporter et d'importer un portefeuille, enregistrez-le dans un endroit sûr et secret. La pharse peut être trouvée plus tard sous l'onglet paramètres",
    "Passphrase": "Mot de passe",
    "Mnemonic": "Mnémonique",
    "SecondCounter": 'Secondes restantes',
    "EmailInfo": "S'il vous plaît, mettez une adresse email valide",
    "OtpInfo": "Entrez l'OTP envoyé sur l'adresse e-mail saisie",
    'OtpInvalid': 'Please enter the valid OTP',
    'OtpSuccess': 'OTP vérifié avec succès',
    'WalletInitialized':'Portefeuille initialisé avec succès.',
  },
  "Terms": {
    "AcceptTerms": "Veuillez accepter les termes et conditions ci-dessous avant d'utiliser cette application.",
    "TermsAndConditions": "Les présentes conditions générales définissent les droits et obligations de tous les utilisateurs concernant l'utilisation du service. Votre accès au service et son utilisation sont conditionnés par votre acceptation et votre respect des présentes conditions générales. Ces conditions générales s'appliquent à tous les visiteurs, utilisateurs et autres personnes qui accèdent ou utilisent le service.",
    "Attestation": "J'ai lu, compris et accepté les termes et conditions."
  },
  "PinCreate": {
    "UserAuthenticationPin": "Broche d'authentification de l'utilisateur",
    "PinMustBe6DigitsInLength": "Le code PIN doit comporter 6 chiffres",
    "ReEnterPinMustBe6DigitsInLength": 'Longueur du code PIN insuffisante',
    "PinsEnteredDoNotMatch": "Le code PIN saisi ne correspond pas", 
    "PinsSuccess": "Code PIN créé avec succès", 
    "PinChange": "Le code PIN a été modifié avec succès",
    "NewPinMatchwithOld": 'La nouvelle broche est identique à une ancienne broche',       
    "6DigitPin": "NIP à 6 chiffres",
    "ReenterPin": "Entrez à nouveau le code PIN",
    "ReenterNewPin": "Entrez à nouveau le nouveau code PIN",
    "Create": "Créer",
    "ValidOldPin": "Veuillez saisir un ancien code PIN valide",
    "WalletCreated": "Votre portefeuille est créé avec succès.",
    "OR": "OU",
    "EmailConfirmation": "Avertissement",
    "CheckEmail": "L'e-mail doit être le même que celui utilisé pour l'exportation du portefeuille.",
    "PinInfo": 'Cette broche utilisée pour la connexion'
  },
  "Biometric": {
    "Biometric": "Biométrique",
    "BiometricConfirm": "Confirmer l'empreinte digitale",
    "BiometricSuccess": "Empreinte digitale configurée avec succès",
    "BiometricFailed": "Échec de la biométrie",
    "BiometricCancle": "L'utilisateur a annulé l'invite biométrique",
    "BiometricNotSupport": "Biométrie non prise en charge",
    "RegisterPinandBiometric": 'Enregistrer le code PIN et la biométrie',
    "BiometricInfo": "S'inscrire Utilisation biométrique pour la connexion"
  },
  "Initialization":{
    "CompleteInitialization":"Complétez votre initialisation",
    "InitializationInfo":"Initialiser le nouveau portefeuille ou importer l'ancien portefeuille",
  },
  "Mnemonic":{
    "MnemonicTitle":"Pour terminer l'initialisation, veuillez créer un Mnémonique"
  },
  "Home": {
    "Welcome": "Bienvenue",
    "Notifications": "Avis",
    "NoNewUpdates": "Vous n'avez aucune nouvelle notification.",
    "NoCredentials": "Vous n'avez pas d'identifiants dans votre portefeuille.",
    "SeeAll": "Voir tout",
    "YouHave": "Tu as",
    "Credential": "justificative",
    "Credentials": "identifiants",
    "InYourWallet": "dans votre portefeuille",
    "CredentialCountUndefinedError":"Le nombre d'informations d'identification ne peut pas être indéfini",
  },
  "PinEnter": {
    "IncorrectPin": "Broche incorrecte",    
  }, 
  "Settings": {
    "ChangePin": "Changer la broche",
    "Version": "Version",
    "AppPreferences": "Préférences de l'application",
    "AboutApp": "À propos de l'application",
    "Language": "Langue",
    "Logout": "Se déconnecter",
    "LogoutMsg": "Voulez-vous vraiment vous déconnecter",
    "MnemonicMsg": 'Le mnémonique ne peut pas être vide',
    "EnterMnemonic": 'Entrez le mnémonique',
    "ValidMnemonic": 'Mnémonique valide',
    "InvalidMnemonic": 'Mnémonique invalide',
    "Yes": "Oui",
    "No": 'Non',
    "ExportWallet": "Portefeuille d'exportation",
    "ViewMnemonic": 'Voir Mnémonique',
  },
  "ExportWallet":{
    "WalletExportedPath": "Portefeuille exporté vers ce chemin :"
  },
  "ImportWallet":{
    "SelectWalletFile": "Sélectionnez le fichier de portefeuille",
    "EmptyMnemonic": 'Les mnémoniques ne peuvent pas être vides',
    "InvalidMnemonic": 'Mnémoniques invalides ',
    "WalletRestoreFailed":'Échec de la restauration du portefeuille',
    "ImportError": "Votre e-mail ou mnémonique est incorrect, veuillez le vérifier attentivement",
  },
  "ConnectionInvitation":{
    "ConsentMessage": "Nouvelle demande de connexion"
  },
  "ContactDetails": {
    "Created": "Créé",
    "ConnectionState": "État de la connexion",
    "AContact": "Un contact",
    "DeleteConnection": "Supprimer la connexion",
    "DeleteConnectionAlert": "Êtes-vous sûr de vouloir supprimer cette connexion ?",
    "DeleteConnectionSuccess": "La connexion a été supprimée avec succès",
    "DeleteConnectionFailed": "Échec de la suppression de la connexion",
    "ConnectionCannotDelete": "La connexion du médiateur ne peut pas être supprimée"
  },
  "Credentials": {
    "CredentialsNotFound": "Identifiants introuvables",
  },
  "CredentialDetails": {
    "Id": "Identifiant:",
    "CreatedAt": "Créé à:",
    "Version": "Version",
    "Issued": "Publié",
    "PrivacyPolicy": "Politique de confidentialité",
    "TermsAndConditions": "Termes et conditions",
    "RemoveFromWallet": "Retirer du portefeuille",
  },
  "CredentialOffer": {
    "ThisIsTakingLongerThanExpected": "Cela prend plus de temps que prévu. Revenez plus tard pour vos nouvelles informations d'identification.",
    "RejectThisCredential?": "Refuser cet identifiant ?",
    "AcceptingCredential": "Acceptation des informations d'identification",
    "SuccessfullyAcceptedCredential": "Informations d'identification acceptées avec succès",
    "RejectingCredential":"Rejeter les informations d'identification",
    "SuccessfullyRejectedCredential":"Identifiant rejeté avec succès",
    "CredentialNotFound": "Identifiant introuvable",
    "CredentialAccepted": "Titre accepté",
    "CredentialRejected": "Identifiant refusé",
    "CredentialAddedToYourWallet": "Identifiant ajouté à votre portefeuille",
    "CredentialDeclined": "Identifiant refusé",
    "CredentialOnTheWay": "Votre accréditation est en route",
    "CredentialOffer": "Nouvelle offre d'accréditation",
    "IsOfferingYouACredential": "vous offre une accréditation",
    "CredentialOfferParamsError":"Les poussettes d'itinéraire CredentialOffer n'ont pas été définies correctement",
    "FetchAFJError":"Impossible de récupérer l'agent de l'AFJ",
    "CredentialFetchError":"Impossible de récupérer les informations d'identification de l'AFJ",
    "RejectOfferTitle":"Impossible de rejeter l'offre",
    "RejectOfferMessage":"Un problème est survenu lors du rejet de l'offre d'identifiants",

  },
  "TabStack": {
    "Home": "Maison",
    "Connections": "Connexion",
    "Scan": "Analyse",
    "Credentials": "Identifiants",
    "Settings": "Réglages",
  },
  "Toasts":{
    "Success": "Succès",
    "Error": "Erreur",
    "Info": "Info",
    "Warning": "Avertissement"
  },
  "ProofRequest": {
    "Title": "<b>{{connection}}</b> fordert eine Verifizierung von Ihrem Wallet an. \n\nSie bitten darum, dass Sie teilen:",
    "OfferDelay": "Retard de l'offre",
    "RejectThisProof?": "Rejeter cette preuve ?",
    "AcceptingProof": "Acceptation de la preuve",
    "SuccessfullyAcceptedProof": "Preuve acceptée avec succès",
    "ProofNotFound": "Preuve introuvable",
    "RejectingProof": "Rejet de la preuve",
    "ProofAccepted": "Preuve acceptée",
    "ProofRejected": "Preuve rejetée",
    "RequestedCredentialsCouldNotBeFound": "Les informations d'identification demandées sont introuvables",
    "ProofRequest": "Nouvelle demande de preuve",
    "NotAvailableInYourWallet": "Rejeter cette preuve ?0",
    "IsRequestng": "Rejeter cette preuve ?1",
    "IsRequestingSomethingYouDontHaveAvailable": "Rejeter cette preuve ?2",
    "IsRequestingYouToShare": "Rejeter cette preuve ?3",
    "WhichYouCanProvideFrom": "Rejeter cette preuve ?4",
    "Details": "Rejeter cette preuve ?5",
    "SendingTheInformationSecurely": "Rejeter cette preuve ?6",
    "InformationSentSuccessfully": "Rejeter cette preuve ?7",
    "ProofRequestDeclined": "Rejeter cette preuve ?8",
    "ProofUpdateErrorTitle": "Impossible de mettre à jour les identifiants récupérés",
    "ProofUpdateErrorMessage": "Un problème est survenu lors de la mise à jour des informations d'identification récupérées",
    "ProofAcceptErrorTitle": "Impossible d'accepter la demande de justificatif",
    "ProofAcceptErrorMessage": "Un problème est survenu lors de l'acceptation de la demande de preuve",
    "ProofRejectErrorTitle": "Impossible de rejeter la demande de justificatif",
    "ProofRejectErrorMessage": "Un problème est survenu lors du rejet de la demande de preuve ",
    "MissingInformation": {
      "Title": "La demande ne peut pas être complétée",
      "AlertMissingInformation": {
        "Title": "Votre portefeuille manque d'informations"
      }
    },
    "ProofRequestParamsError":"Les poussettes d'itinéraire ProofRequest n'ont pas été correctement définies",
    "FetchProofError":"Impossible de récupérer la preuve auprès de l'AFJ",
  },
  "Record": {
    "Hide": "Cacher",
    "Show": "Montrer",
    "HideAll": "Cacher tout",
    "Hidden": "Caché",
  },
  "QRScanner":{
    "PermissionToUseCamera":"Autorisation d'utiliser l'appareil photo",
    "PermissionMessage":"Nous avons besoin de votre autorisation pour utiliser votre appareil photo",
    "NotAValidURL":"URL non valide",
    "InvalidQrCode":"QrCode invalide",
  },
}
export default translation
